### PR TITLE
Add benchmarks using tox and hyperfine

### PR DESCRIPTION
**Pull request by rhpvorderman**
WIP

### CODE REVIEW

**Comment by rhpvorderman** [comment]
Short inbetween update. Pyfastx looked really dangerous. At a quick glance: memchr, extension written in C (no Cython overhead). Yet  it is 2x slower than dnaio. So we can rest easy. Pyfastx is quite a nice project though. Documentation is good. It is quite popular. But it doesn't offer paired reading or writing facilities.

Fastq-and-furious is not so good to put it mildly. It requires  some thorough reading to use the 'fast' C-extension. And then that turns out to be slower than Pyfastx. 

The other python solutions I just know to be slower than dnaio. I will add benchmarks later. On gzip dnaio is the only project which uses python-isal so it is going to smash the competition.

So now I really want to compile some simple C++ code that mimicks the read scripts and uses fastp. That uses ISA-L and should be some real competition. (But it does not use memchr, and the C++ idiomatic way sucks, so dnaio will probably smash it too...).

**Comment by rhpvorderman** [comment]
```
Benchmark #1: python dnaio/read.py ../data/single43bp.fastq
  Time (mean ± σ):      1.413 s ±  0.050 s    [User: 1.269 s, System: 0.143 s]
  Range (min … max):    1.354 s …  1.498 s    10 runs

Benchmark 1: fastp/read_program ../data/single43bp.fastq
  Time (mean ± σ):      2.441 s ±  0.034 s    [User: 1.998 s, System: 0.442 s]
  Range (min … max):    2.379 s …  2.497 s    10 runs
```

The fastp program has been compiled with -O3. So no excuses. I already have a strong bias against C++ and it was further confirmed. If you want speed: go C. EDIT: The biased comments on C++ were written when fastp was more than two times slower than dnaio. The reason turned out to be a memory leak that I caused. I have fixed it, and dnaio is still clearly the fastest. Fastp is however the fastest library *with a journal paper* out there.

There needs to be a C++ program in the paper to parry the "but in python everything is slow anyway, so this is irrelevant, since C++ will be faster" argument. It will need to be phrased more eloquently of course. Fastp is immensely popular so it fits as a good comparison. EDIT: Checking the structure of fastp a bit more, it is also the library that is most comparable to dnaio in terms of features: paired-end reading, writer structures, using ISA-L. Therefore it is the most comparable, even though it is in another language.

**Comment by rhpvorderman** [comment]
Whoops, fastp was slow due to a memory leak in my benchmark program... :man_facepalming: . This is fixed now and I updated the results.

I ran into a problem with regards to the writing. dnaio provides separate `Writer` classes and it supports using `fastq_bytes()` to write to a stream directly. The latter is faster. The latter method is also supported by pyfastx (using the `raw` attribute). Other libraries do support these writer classes. So I don't know how to fairly assess performance here, other than make two distinct categories. What are your thoughts on this?

**Comment by rhpvorderman** [comment]
@marcelm, it is done. This should generate all the comparison data that is needed for a paper. All that remains is adding some scripts to parse all the generated JSON files, but that depends on how the tables will be represented, so I will leave that for another time.

I still need to do one complete run to check if all the tox commands are correct. I will do that tomorrow. Some of these tools take a really long time.

**Comment by marcelm** [comment]
Oh wow, that is really impressive work! Very nice usage of tox, haven’t done anything like this so far. This might come in handy.

I have now reserved Oct. 6th and onwards in the calendar for writing the paper; that’s the earliest possible.

I saw your comment regarding Python 3.11. I benchmarked Cutadapt and was quite impressed with the speedup (20-25%), so we should definitely re-run the dnaio benchmarks with 3.11 for the final numbers.

**Comment by marcelm** [comment]
And please merge when you did the complete run.

**Comment by rhpvorderman** [comment]
> I have now reserved Oct. 6th and onwards in the calendar for writing the paper; that’s the earliest possible.

Good to know. Please let me know if there is anything I can do. I have enough room in my schedule to accomodate.

> I saw your comment regarding Python 3.11. I benchmarked Cutadapt and was quite impressed with the speedup (20-25%), so we should definitely re-run the dnaio benchmarks with 3.11 for the final numbers.

Yes, there is now a faster CPython project going on, spearheaded by Mark Shannon and Guido van Rossum. See also https://peps.python.org/pep-0659/ . 3.11 and 3.12 are going to implement these changes (in the PEP it states 3.10 and 3.11, but I believe they have postponed them one minor version). 3.11 is now already available as release candidate, so it will probably be available soon. And if not we can simply benchmark the release candidate.

**Comment by rhpvorderman** [comment]
>  Very nice usage of tox, haven’t done anything like this so far. This might come in handy.

I was not entirely happy with the tox configuration having so much repetition. I was able to fix that using tox more advanced options, such as environment-name dependent installation. Check it out, it is quite handy.

**Pull request merged**
